---
- name: Install and configure Zabbix agent
  hosts: test_server
  become: yes

  tasks:  
  - name: Update apt packages
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Zabbix agent
    apt:
      name: zabbix-agent
      state: latest
      install_recommends: no

  - name: Configure Zabbix
    lineinfile:
      dest: /etc/zabbix/zabbix_agentd.conf
      regexp: "{{item.regexp}}"
      line: "{{item.line}}"
    with_items:
      - { regexp: '^Server=', line: 'Server=192.168.0.107' }
      - { regexp: '^ServerActive=', line: 'ServerActive=192.168.0.107' }
      - { regexp: '^Hostname=', line: 'Hostname={{hostname}}' } 
      - { regexp: '^# Timeout=', line: 'Timeout=10' } 
   
  - name: Srart Zabbix agent 
    service: 
      name: zabbix-agent
      enabled: yes
      state: restarted
